// ========================================
// AUTO-GENERATED DATA (DO NOT EDIT MANUALLY)
// Run: node generate-data.js  to regenerate from Excel files
// ========================================
export const SANCTION_III = [
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Promotion 85%",
    "SC": 6,
    "ST": 4,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 33,
    "TOTAL": 49
  },
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 9
  },
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Promotion 85%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 9,
    "TOTAL": 14
  },
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 3
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 5,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 7,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 19,
    "TOTAL": 39
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 8
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Promotion 10%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 3,
    "TOTAL": 5
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 8,
    "ST": 4,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 11,
    "SEBC": 2,
    "EWS": 2,
    "OPEN": 23,
    "TOTAL": 57
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 11
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Promotion 10%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 5,
    "TOTAL": 8
  },
  {
    "circle": "RPUC",
    "designation": "Chief Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 3,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 17,
    "TOTAL": 25
  },
  {
    "circle": "RPUC",
    "designation": "Principal Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 18,
    "ST": 10,
    "VJ-A": 4,
    "NT-B": 4,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 90,
    "TOTAL": 137
  },
  {
    "circle": "RPUC",
    "designation": "Principal Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 30,
    "TOTAL": 45
  },
  {
    "circle": "RPUC",
    "designation": "Senior Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 31,
    "TOTAL": 46
  },
  {
    "circle": "RPUC",
    "designation": "Operator",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 36,
    "ST": 19,
    "VJ-A": 8,
    "NT-B": 7,
    "NT-C": 10,
    "NT-D": 5,
    "SBC": 5,
    "OBC": 52,
    "SEBC": 12,
    "EWS": 12,
    "OPEN": 107,
    "TOTAL": 273
  },
  {
    "circle": "RPUC",
    "designation": "Vehicle Driver",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 4,
    "TOTAL": 10
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Promotion 85%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 29,
    "TOTAL": 43
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 8
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Promotion 85%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 8,
    "TOTAL": 12
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 2
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 7,
    "ST": 4,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 10,
    "SEBC": 2,
    "EWS": 2,
    "OPEN": 21,
    "TOTAL": 53
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 11
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Promotion 10%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 5,
    "TOTAL": 7
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 5,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 6,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 15,
    "TOTAL": 34
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 7
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Promotion 10%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 3,
    "TOTAL": 4
  },
  {
    "circle": "GKUC",
    "designation": "Chief Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 3,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 15,
    "TOTAL": 22
  },
  {
    "circle": "GKUC",
    "designation": "Principal Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 15,
    "ST": 8,
    "VJ-A": 4,
    "NT-B": 3,
    "NT-C": 4,
    "NT-D": 2,
    "SBC": 2,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 79,
    "TOTAL": 117
  },
  {
    "circle": "GKUC",
    "designation": "Principal Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 30,
    "TOTAL": 45
  },
  {
    "circle": "GKUC",
    "designation": "Senior Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 30,
    "TOTAL": 45
  },
  {
    "circle": "GKUC",
    "designation": "Operator",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 35,
    "ST": 19,
    "VJ-A": 8,
    "NT-B": 7,
    "NT-C": 10,
    "NT-D": 5,
    "SBC": 5,
    "OBC": 51,
    "SEBC": 12,
    "EWS": 12,
    "OPEN": 106,
    "TOTAL": 270
  },
  {
    "circle": "GKUC",
    "designation": "Vehicle Driver",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 8
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Promotion 85%",
    "SC": 5,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 26,
    "TOTAL": 39
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 7
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Promotion 85%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 6,
    "TOTAL": 9
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 1
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 6,
    "ST": 4,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 9,
    "SEBC": 2,
    "EWS": 3,
    "OPEN": 18,
    "TOTAL": 48
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 10
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Promotion 10%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 6
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 3,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 4,
    "SEBC": 2,
    "EWS": 2,
    "OPEN": 7,
    "TOTAL": 24
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 5
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Promotion 10%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 3
  },
  {
    "circle": "PRC",
    "designation": "Chief Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 3,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 15,
    "TOTAL": 22
  },
  {
    "circle": "PRC",
    "designation": "Principal Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 12,
    "ST": 6,
    "VJ-A": 3,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 2,
    "SBC": 2,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 61,
    "TOTAL": 91
  },
  {
    "circle": "PRC",
    "designation": "Principal Operator",
    "sanctionType": "By Promotion 100%",
    "SC": 5,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 25,
    "TOTAL": 37
  },
  {
    "circle": "PRC",
    "designation": "Senior Operator",
    "sanctionType": "By Promotion 100%",
    "SC": 5,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 25,
    "TOTAL": 38
  },
  {
    "circle": "PRC",
    "designation": "Operator",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 29,
    "ST": 16,
    "VJ-A": 7,
    "NT-B": 6,
    "NT-C": 8,
    "NT-D": 4,
    "SBC": 4,
    "OBC": 43,
    "SEBC": 14,
    "EWS": 14,
    "OPEN": 80,
    "TOTAL": 225
  },
  {
    "circle": "PRC",
    "designation": "Vehicle Driver",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 5,
    "TOTAL": 7
  }
];
export const SANCTION_IV = [
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 12
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 4,
    "TOTAL": 13
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 4,
    "TOTAL": 13
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 4,
    "TOTAL": 13
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 10
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 3,
    "SEBC": 2,
    "EWS": 1,
    "OPEN": 4,
    "TOTAL": 15
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 3,
    "SEBC": 2,
    "EWS": 2,
    "OPEN": 4,
    "TOTAL": 16
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 12
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 10
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "division": "Mulshi Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 3
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 3,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 4,
    "SEBC": 2,
    "EWS": 2,
    "OPEN": 6,
    "TOTAL": 22
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 5
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 5
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 5
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 5
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 7
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 6
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 5
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 3,
    "SEBC": 2,
    "EWS": 2,
    "OPEN": 5,
    "TOTAL": 17
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 7
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 8
  },
  {
    "circle": "PRC",
    "division": "Pune Mulshi Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 11
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 10,
    "ST": 6,
    "VJ-A": 2,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 51,
    "TOTAL": 76
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 10,
    "ST": 6,
    "VJ-A": 2,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 2,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 54,
    "TOTAL": 80
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 11,
    "ST": 6,
    "VJ-A": 2,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 2,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 54,
    "TOTAL": 81
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 10,
    "ST": 6,
    "VJ-A": 2,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 2,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 54,
    "TOTAL": 80
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 8,
    "ST": 4,
    "VJ-A": 2,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 41,
    "TOTAL": 62
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 12,
    "ST": 7,
    "VJ-A": 3,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 2,
    "SBC": 2,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 63,
    "TOTAL": 94
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 13,
    "ST": 7,
    "VJ-A": 3,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 2,
    "SBC": 2,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 66,
    "TOTAL": 98
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 10,
    "ST": 5,
    "VJ-A": 2,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 50,
    "TOTAL": 74
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 8,
    "ST": 4,
    "VJ-A": 2,
    "NT-B": 2,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 42,
    "TOTAL": 62
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 25,
    "ST": 14,
    "VJ-A": 6,
    "NT-B": 5,
    "NT-C": 6,
    "NT-D": 4,
    "SBC": 4,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 131,
    "TOTAL": 195
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 24,
    "ST": 13,
    "VJ-A": 5,
    "NT-B": 5,
    "NT-C": 6,
    "NT-D": 4,
    "SBC": 4,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 123,
    "TOTAL": 184
  },
  {
    "circle": "PRC",
    "division": "Pune Mulshi Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 24,
    "ST": 13,
    "VJ-A": 6,
    "NT-B": 5,
    "NT-C": 6,
    "NT-D": 4,
    "SBC": 3,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 122,
    "TOTAL": 183
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 21,
    "ST": 11,
    "VJ-A": 5,
    "NT-B": 4,
    "NT-C": 6,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 30,
    "SEBC": 10,
    "EWS": 10,
    "OPEN": 57,
    "TOTAL": 160
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 17,
    "ST": 9,
    "VJ-A": 4,
    "NT-B": 3,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 25,
    "SEBC": 5,
    "EWS": 5,
    "OPEN": 52,
    "TOTAL": 131
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 19,
    "ST": 10,
    "VJ-A": 4,
    "NT-B": 4,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 28,
    "SEBC": 10,
    "EWS": 10,
    "OPEN": 51,
    "TOTAL": 147
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 20,
    "ST": 11,
    "VJ-A": 5,
    "NT-B": 5,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 29,
    "SEBC": 8,
    "EWS": 8,
    "OPEN": 57,
    "TOTAL": 154
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 15,
    "ST": 8,
    "VJ-A": 4,
    "NT-B": 3,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 22,
    "SEBC": 6,
    "EWS": 6,
    "OPEN": 43,
    "TOTAL": 118
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 24,
    "ST": 13,
    "VJ-A": 6,
    "NT-B": 5,
    "NT-C": 7,
    "NT-D": 4,
    "SBC": 4,
    "OBC": 35,
    "SEBC": 8,
    "EWS": 8,
    "OPEN": 72,
    "TOTAL": 186
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 25,
    "ST": 13,
    "VJ-A": 6,
    "NT-B": 5,
    "NT-C": 6,
    "NT-D": 4,
    "SBC": 4,
    "OBC": 37,
    "SEBC": 10,
    "EWS": 10,
    "OPEN": 72,
    "TOTAL": 192
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 18,
    "ST": 10,
    "VJ-A": 4,
    "NT-B": 3,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 26,
    "SEBC": 10,
    "EWS": 10,
    "OPEN": 47,
    "TOTAL": 139
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 18,
    "ST": 9,
    "VJ-A": 4,
    "NT-B": 3,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 26,
    "SEBC": 7,
    "EWS": 7,
    "OPEN": 51,
    "TOTAL": 136
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 19,
    "ST": 10,
    "VJ-A": 4,
    "NT-B": 4,
    "NT-C": 5,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 27,
    "SEBC": 11,
    "EWS": 11,
    "OPEN": 48,
    "TOTAL": 145
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 22,
    "ST": 12,
    "VJ-A": 5,
    "NT-B": 4,
    "NT-C": 6,
    "NT-D": 4,
    "SBC": 3,
    "OBC": 32,
    "SEBC": 13,
    "EWS": 13,
    "OPEN": 56,
    "TOTAL": 170
  },
  {
    "circle": "PRC",
    "division": "Pune Mulshi Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 18,
    "ST": 10,
    "VJ-A": 4,
    "NT-B": 3,
    "NT-C": 6,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 26,
    "SEBC": 10,
    "EWS": 10,
    "OPEN": 43,
    "TOTAL": 136
  }
];
export const FILLED_III_MASTER = [
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Promotion 85%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 48,
    "TOTAL": 48
  },
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 2
  },
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Promotion 85%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 8,
    "TOTAL": 12
  },
  {
    "circle": "RPUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 3
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 5,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 7,
    "SEBC": 0,
    "EWS": 2,
    "OPEN": 19,
    "TOTAL": 38
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Internal Notification 15%",
    "SC": 2,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 3,
    "TOTAL": 5
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Promotion 10%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 5
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 7,
    "ST": 4,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 3,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 23,
    "TOTAL": 42
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "RPUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Promotion 10%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 7,
    "TOTAL": 7
  },
  {
    "circle": "RPUC",
    "designation": "Chief Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 20,
    "TOTAL": 22
  },
  {
    "circle": "RPUC",
    "designation": "Principal Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 8,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 2,
    "NT-C": 1,
    "NT-D": 2,
    "SBC": 2,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 96,
    "TOTAL": 114
  },
  {
    "circle": "RPUC",
    "designation": "Principal Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 4,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 33,
    "TOTAL": 43
  },
  {
    "circle": "RPUC",
    "designation": "Senior Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 2,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 40,
    "TOTAL": 46
  },
  {
    "circle": "RPUC",
    "designation": "Operator",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 10,
    "ST": 8,
    "VJ-A": 8,
    "NT-B": 4,
    "NT-C": 4,
    "NT-D": 6,
    "SBC": 3,
    "OBC": 17,
    "SEBC": 7,
    "EWS": 1,
    "OPEN": 76,
    "TOTAL": 144
  },
  {
    "circle": "RPUC",
    "designation": "Vehicle Driver",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 2
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Promotion 85%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 29,
    "TOTAL": 43
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 1,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 8
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Promotion 85%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 11,
    "TOTAL": 12
  },
  {
    "circle": "GKUC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 5,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 4,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 14,
    "TOTAL": 27
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 2
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Promotion 10%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 3,
    "TOTAL": 4
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 4,
    "ST": 4,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 5,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 20,
    "TOTAL": 36
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1
  },
  {
    "circle": "GKUC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Promotion 10%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 7,
    "TOTAL": 7
  },
  {
    "circle": "GKUC",
    "designation": "Chief Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 16,
    "TOTAL": 19
  },
  {
    "circle": "GKUC",
    "designation": "Principal Technician",
    "sanctionType": "By Promotion 10%",
    "SC": 6,
    "ST": 2,
    "VJ-A": 2,
    "NT-B": 0,
    "NT-C": 3,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 103,
    "TOTAL": 117
  },
  {
    "circle": "GKUC",
    "designation": "Principal Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 2,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 38,
    "TOTAL": 45
  },
  {
    "circle": "GKUC",
    "designation": "Senior Operator",
    "sanctionType": "By Promotion 10%",
    "SC": 2,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 37,
    "TOTAL": 45
  },
  {
    "circle": "GKUC",
    "designation": "Operator",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 17,
    "ST": 9,
    "VJ-A": 5,
    "NT-B": 3,
    "NT-C": 9,
    "NT-D": 5,
    "SBC": 4,
    "OBC": 16,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 76,
    "TOTAL": 145
  },
  {
    "circle": "GKUC",
    "designation": "Vehicle Driver",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Promotion 85%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 38,
    "TOTAL": 39
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(AC)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Promotion 85%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 8,
    "TOTAL": 9
  },
  {
    "circle": "PRC",
    "designation": "Upper Division Clerk(HR)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 2,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 7,
    "TOTAL": 12
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk(HR)/OA",
    "sanctionType": "By Promotion 10%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 2
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 12,
    "TOTAL": 14
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Internal Notification 15%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "designation": "Lower Division Clerk (Accounts)",
    "sanctionType": "By Promotion 10%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "designation": "Chief Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 22,
    "TOTAL": 22
  },
  {
    "circle": "PRC",
    "designation": "Principal Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 4,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 2,
    "NT-C": 3,
    "NT-D": 2,
    "SBC": 2,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 74,
    "TOTAL": 91
  },
  {
    "circle": "PRC",
    "designation": "Principal Operator",
    "sanctionType": "By Promotion 100%",
    "SC": 0,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 31,
    "TOTAL": 37
  },
  {
    "circle": "PRC",
    "designation": "Senior Operator",
    "sanctionType": "By Promotion 100%",
    "SC": 2,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 33,
    "TOTAL": 38
  },
  {
    "circle": "PRC",
    "designation": "Operator",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 13,
    "VJ-A": 4,
    "NT-B": 0,
    "NT-C": 2,
    "NT-D": 2,
    "SBC": 3,
    "OBC": 10,
    "SEBC": 0,
    "EWS": 4,
    "OPEN": 26,
    "TOTAL": 70
  },
  {
    "circle": "PRC",
    "designation": "Vehicle Driver",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 1
  }
];
export const FILLED_IV_MASTER = [
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 3,
    "TOTAL": 8
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 8
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 5,
    "TOTAL": 10
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 4,
    "TOTAL": 11
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 8
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 4,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 12
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 3,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 10
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 3,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 3,
    "TOTAL": 7
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 9
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "PRC",
    "division": "Mulshi Division",
    "designation": "Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 6,
    "TOTAL": 14
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 3
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 4
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 5
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 5
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 5
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 5
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 5
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 2,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 5,
    "TOTAL": 11
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 3,
    "TOTAL": 4
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 6
  },
  {
    "circle": "PRC",
    "division": "Mulshi Division",
    "designation": "PEON",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 8
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 4,
    "ST": 2,
    "VJ-A": 2,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 2,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 58,
    "TOTAL": 69
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 2,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 3,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 51,
    "TOTAL": 61
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 0,
    "ST": 2,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 62,
    "TOTAL": 69
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 2,
    "ST": 3,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 56,
    "TOTAL": 67
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 3,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 54,
    "TOTAL": 60
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 3,
    "ST": 5,
    "VJ-A": 1,
    "NT-B": 2,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 80,
    "TOTAL": 94
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 3,
    "ST": 0,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 89,
    "TOTAL": 98
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 1,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 68,
    "TOTAL": 74
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 2,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 2,
    "NT-C": 2,
    "NT-D": 3,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 50,
    "TOTAL": 62
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 2,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 103,
    "TOTAL": 108
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 3,
    "ST": 4,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 2,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 147,
    "TOTAL": 158
  },
  {
    "circle": "PRC",
    "division": "Pune Mulshi Division",
    "designation": "Senior Technician",
    "sanctionType": "By Promotion 100%",
    "SC": 7,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 2,
    "SBC": 3,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 106,
    "TOTAL": 122
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 10,
    "ST": 1,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 4,
    "SBC": 2,
    "OBC": 9,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 32,
    "TOTAL": 63
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 9,
    "ST": 2,
    "VJ-A": 3,
    "NT-B": 2,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 2,
    "OBC": 14,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 33,
    "TOTAL": 68
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 9,
    "ST": 4,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 2,
    "OBC": 9,
    "SEBC": 2,
    "EWS": 0,
    "OPEN": 20,
    "TOTAL": 48
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 7,
    "ST": 2,
    "VJ-A": 3,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 1,
    "SBC": 2,
    "OBC": 6,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 20,
    "TOTAL": 42
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 4,
    "VJ-A": 3,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 2,
    "SBC": 1,
    "OBC": 9,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 25,
    "TOTAL": 52
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 14,
    "ST": 4,
    "VJ-A": 3,
    "NT-B": 2,
    "NT-C": 2,
    "NT-D": 3,
    "SBC": 0,
    "OBC": 18,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 48,
    "TOTAL": 94
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 16,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 2,
    "NT-D": 4,
    "SBC": 3,
    "OBC": 16,
    "SEBC": 1,
    "EWS": 0,
    "OPEN": 45,
    "TOTAL": 89
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 2,
    "NT-D": 1,
    "SBC": 2,
    "OBC": 9,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 18,
    "TOTAL": 42
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 7,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 3,
    "SBC": 3,
    "OBC": 12,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 24,
    "TOTAL": 53
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 8,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 13
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 4,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 10,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 4,
    "TOTAL": 22
  },
  {
    "circle": "PRC",
    "division": "Mulshi Division",
    "designation": "Technician",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 6,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 3,
    "TOTAL": 12
  }
];
export const SURPLUS_III = [
  {
    "circle": "RPUC",
    "designation": "Junior Assistant(HR)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Lower Division Clerk(HR)/OA",
      "sanctionType": "By Direct Recruitment 75%",
      "circle": "RPUC"
    }
  },
  {
    "circle": "RPUC",
    "designation": "Junior Assistant (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 3,
    "SEBC": 2,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 6,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Lower Division Clerk (Accounts)",
      "sanctionType": "By Direct Recruitment 75%",
      "circle": "RPUC"
    }
  },
  {
    "circle": "RPUC",
    "designation": "Upkendra Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Operator",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC"
    }
  },
  {
    "circle": "GKUC",
    "designation": "Junior Assistant(HR)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 2,
    "TOTAL": 6,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Lower Division Clerk(HR)/OA",
      "sanctionType": "By Direct Recruitment 75%",
      "circle": "GKUC"
    }
  },
  {
    "circle": "GKUC",
    "designation": "Junior Assistant (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 2,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 3,
    "SEBC": 2,
    "EWS": 1,
    "OPEN": 1,
    "TOTAL": 11,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Lower Division Clerk (Accounts)",
      "sanctionType": "By Direct Recruitment 75%",
      "circle": "GKUC"
    }
  },
  {
    "circle": "GKUC",
    "designation": "Upkendra Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 2,
    "TOTAL": 6,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Operator",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC"
    }
  },
  {
    "circle": "PRC",
    "designation": "Junior Assistant(HR)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 0,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 2,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 0,
    "TOTAL": 7,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Lower Division Clerk(HR)/OA",
      "sanctionType": "By Direct Recruitment 75%",
      "circle": "PRC"
    }
  },
  {
    "circle": "PRC",
    "designation": "Junior Assistant (Accounts)",
    "sanctionType": "By Direct Recruitment 75%",
    "SC": 3,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 4,
    "SEBC": 2,
    "EWS": 0,
    "OPEN": 5,
    "TOTAL": 19,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Lower Division Clerk (Accounts)",
      "sanctionType": "By Direct Recruitment 75%",
      "circle": "PRC"
    }
  },
  {
    "circle": "PRC",
    "designation": "Tracer",
    "sanctionType": "Surplus (Adjusted)",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Lower Division Clerk (Accounts)",
      "sanctionType": "By Direct Recruitment 75%",
      "circle": "PRC"
    }
  },
  {
    "circle": "PRC",
    "designation": "Upkendra Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Operator",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC"
    }
  }
];
export const SURPLUS_IV = [
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 0,
    "TOTAL": 2,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Rastapeth Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Bundgarden Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Padmavati Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Parvati Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Nagar Road Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Pimpri Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 0,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Bhosari  Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 2,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Kothrud Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Shivajinagar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Manchar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Rajgurunagar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Mulshi Division",
    "designation": "Assistant- Junior Office Assistant",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 1,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 1,
    "TOTAL": 3,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Junior Office Assistant",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Mulshi Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 1,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 1,
    "OPEN": 0,
    "TOTAL": 4,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Rastapeth Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Bundgarden Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Padmavati Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Parvati Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Nagar Road Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Pimpri Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Bhosari  Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Kothrud Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Shivajinagar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 1,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Manchar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 1,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 1,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Rajgurunagar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Mulshi Division",
    "designation": "Sahayyak -Peon",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 0,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 0,
    "SEBC": 0,
    "EWS": 0,
    "OPEN": 0,
    "TOTAL": 0,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "PEON",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Mulshi Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Rastapeth Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 2,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 12,
    "SEBC": 4,
    "EWS": 1,
    "OPEN": 10,
    "TOTAL": 39,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Rastapeth Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Bundgarden Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 4,
    "ST": 2,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 3,
    "SEBC": 3,
    "EWS": 0,
    "OPEN": 9,
    "TOTAL": 24,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Bundgarden Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Padmavati Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 1,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 12,
    "SEBC": 5,
    "EWS": 3,
    "OPEN": 13,
    "TOTAL": 45,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Padmavati Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Parvati Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 3,
    "VJ-A": 0,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 2,
    "SBC": 0,
    "OBC": 12,
    "SEBC": 5,
    "EWS": 2,
    "OPEN": 17,
    "TOTAL": 49,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Parvati Division"
    }
  },
  {
    "circle": "RPUC",
    "division": "Pune Nagar Road Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 5,
    "ST": 0,
    "VJ-A": 0,
    "NT-B": 0,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 8,
    "SEBC": 4,
    "EWS": 3,
    "OPEN": 5,
    "TOTAL": 27,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "RPUC",
      "division": "Pune Nagar Road Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Pimpri Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 1,
    "NT-D": 1,
    "SBC": 0,
    "OBC": 9,
    "SEBC": 5,
    "EWS": 4,
    "OPEN": 14,
    "TOTAL": 44,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Pimpri Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Bhosari  Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 5,
    "ST": 5,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 13,
    "SEBC": 5,
    "EWS": 7,
    "OPEN": 11,
    "TOTAL": 49,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Bhosari  Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Kothrud Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 6,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 2,
    "SBC": 0,
    "OBC": 11,
    "SEBC": 5,
    "EWS": 3,
    "OPEN": 12,
    "TOTAL": 42,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Kothrud Division"
    }
  },
  {
    "circle": "GKUC",
    "division": "Pune Shivajinagar Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 7,
    "ST": 2,
    "VJ-A": 1,
    "NT-B": 0,
    "NT-C": 0,
    "NT-D": 0,
    "SBC": 0,
    "OBC": 10,
    "SEBC": 4,
    "EWS": 2,
    "OPEN": 13,
    "TOTAL": 39,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "GKUC",
      "division": "Pune Shivajinagar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Manchar Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 10,
    "ST": 3,
    "VJ-A": 1,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 12,
    "SEBC": 5,
    "EWS": 11,
    "OPEN": 21,
    "TOTAL": 66,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Manchar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Rajgurunagar Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 13,
    "ST": 2,
    "VJ-A": 2,
    "NT-B": 1,
    "NT-C": 0,
    "NT-D": 1,
    "SBC": 1,
    "OBC": 13,
    "SEBC": 8,
    "EWS": 14,
    "OPEN": 29,
    "TOTAL": 84,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Rajgurunagar Division"
    }
  },
  {
    "circle": "PRC",
    "division": "Mulshi Division",
    "designation": "Vidut Sahayyak",
    "sanctionType": "By Direct Recruitment 100%",
    "SC": 10,
    "ST": 1,
    "VJ-A": 2,
    "NT-B": 0,
    "NT-C": 2,
    "NT-D": 2,
    "SBC": 2,
    "OBC": 12,
    "SEBC": 4,
    "EWS": 8,
    "OPEN": 25,
    "TOTAL": 68,
    "isSurplus": true,
    "adjustedAgainst": {
      "designation": "Technician",
      "sanctionType": "By Direct Recruitment 100%",
      "circle": "PRC",
      "division": "Mulshi Division"
    }
  }
];